plugins {
    id 'multiloader-common-provider'
    id 'net.neoforged.moddev'
    id 'publish-local'
}

neoForge {
    neoFormVersion = neo_form_version

    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }

    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
}

dependencies {
    compileOnly "io.github.fishstiz.fidgetz:fidgetz-common:$fidgetz_version"

    compileOnly "org.spongepowered:mixin:$mixin_version"
    compileOnly "io.github.llamalad7:mixinextras-common:$mixinextras_version"
    annotationProcessor "io.github.llamalad7:mixinextras-common:$mixinextras_version"
}