plugins {
    id 'multiloader-common'
}

class LoaderExtension {
    final Property<String> commonPath

    LoaderExtension(ObjectFactory objects) {
        Property<String> prop = objects.property(String) as Property<String>
        prop.convention(":common")
        commonPath = prop
    }
}

def loaderExtension = extensions.create('loader', LoaderExtension)

configurations {
    commonJava {
        canBeResolved = true
    }
    commonResources {
        canBeResolved = true
    }
}

configurations {
    commonJava { canBeResolved = true }
    commonResources { canBeResolved = true }
}

configurations.compileOnly.dependencies.addLater(
        loaderExtension.commonPath.map { path -> dependencies.project(path: path) }
)

configurations.commonJava.dependencies.addLater(
        loaderExtension.commonPath.map { path ->
            dependencies.project(path: path, configuration: 'commonJava')
        }
)

configurations.commonResources.dependencies.addLater(
        loaderExtension.commonPath.map { path ->
            dependencies.project(path: path, configuration: 'commonResources')
        }
)

tasks.named('compileJava', JavaCompile) {
    dependsOn(configurations.commonJava)
    source(configurations.commonJava)
}

processResources {
    dependsOn(configurations.commonResources)
    from(configurations.commonResources)
}

tasks.named('sourcesJar', Jar) {
    dependsOn(configurations.commonJava)
    from(configurations.commonJava)
    dependsOn(configurations.commonResources)
    from(configurations.commonResources)
}
