import me.modmuss50.mpp.ReleaseType

plugins {
    id 'fabric-loom' version "$loom_version" apply false
    id 'net.neoforged.moddev' version "$moddev_version" apply false
    id 'me.modmuss50.mod-publish-plugin'
}

group = maven_group
version = mod_version

publishMods {
    dryRun = Boolean.valueOf(dry_run)
    type = ReleaseType.of(release_type)
    changelog = file("CHANGELOG.md").text

    github {
        accessToken = findProperty("GITHUB_TOKEN") ?: ""
        repository = "fishstiz/packed_packs"
        commitish = "mc/$minecraft_version"
        version = mod_version
        tagName = "v${this.version}"
        displayName = "v${this.version}"
        allowEmptyFiles = true
    }
}
