# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Project
archives_base_name=packed_packs
maven_group=io.github.fishstiz.packed_packs
mod_version=2.1.0+1.21.9
mod_id=packed_packs
mod_name=Packed Packs
mod_author=fishstiz
mod_description=Pack packs into profiles with multiple selection, drag and drop, and extended mouse and keyboard controls.
java_version=21
license=MIT
sources=https://github.com/fishstiz/packed_packs
issues=https://github.com/fishstiz/packed_packs/issues
credits=StarmanMine142, iceban, qznfbnj
minecraft_version=1.21.9
modrinth_id=8Pq6Exn2
curseforge_id=1260514

# Common
moddev_version=2.0.107
neo_form_version=1.21.9-20250930.151910
parchment_minecraft=1.21.9
parchment_version=2025.10.05
mixin_version=0.8.7
mixinextras_version=0.5.0
mod_publish_version=0.8.4
resourcify_version=mrfZqvOq
respackopts_version=4.13.9+forge
libjf_resource_pack_entry_widgets_version=3.17.0-SNAPSHOT

# Fabric
loom_version=1.11-SNAPSHOT
fabric_loader_version=0.17.2
fabric_api_version=0.134.0+1.21.9
fabric_minecraft_version_range=>=1.21.9 <=1.21.10
modmenu_version=16.0.0-rc.1

# NeoForge
neoforge_version=21.9.16-beta
neoforge_loader_version_range=[4,)
neoforge_version_range=[21.9.0,)
neoforge_minecraft_version_range=[1.21.9,1.21.10]
