# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Project
archives_base_name=packed_packs
maven_group=io.github.fishstiz.packed_packs
mod_version=2.2.0-alpha.1+26.1
mod_id=packed_packs
mod_name=Packed Packs
mod_author=fishstiz
mod_description=Pack packs into profiles with multiple selection, drag and drop, and extended mouse and keyboard controls.
java_version=25
license=MIT
sources=https://github.com/fishstiz/packed_packs
issues=https://github.com/fishstiz/packed_packs/issues1
credits=StarmanMine142, iceban, qznfbnj
minecraft_version=26.1

# Common
moddev_version=2.0.140
neo_form_version=26.1-1

# Fabric
loom_version=1.15-SNAPSHOT
fabric_loader_version=0.18.4
fabric_api_version=0.143.15+26.1
fabric_minecraft_version_range=~26.1

# NeoForge
neoforge_version=26.1.0.1-beta
neoforge_loader_version_range=[4,)
neoforge_version_range=[26.1.0.0-alpha.0,)
neoforge_minecraft_version_range=[26.1-rc-1,26.2)

# Publishing
dry_run=true
release_type=ALPHA
modrinth_id=8Pq6Exn2
curseforge_id=1260514
modrinth_versions=26.1,26.1.1,26.1.2
curseforge_versions=26.1,26.1.1,26.1.2