plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
    id 'publish-local'
}

loader {
    commonPath = ':api:common'
}

neoForge {
    version = neoforge_version

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    compileOnly libs.fidgetz.neoforge
}