plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
    id 'publish-local'
}

loader {
    commonPath = ':api:common'
}

neoForge {
    version = neoforge_version

    parchment {
        minecraftVersion = minecraft_version
        mappingsVersion = parchment_version
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}