plugins {
    id 'multiloader-loader'
    id 'net.fabricmc.fabric-loom'
}

loader {
    commonPath = ':testmod:common'
}

repositories {
    exclusiveContent {
        forRepository {
            maven {
                name = "Terraformers"
                url = "https://maven.terraformersmc.com/"
            }
        }
        filter {
            includeModule("com.terraformersmc", "modmenu")
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:$minecraft_version"
    implementation "net.fabricmc:fabric-loader:$fabric_loader_version"
    implementation "net.fabricmc.fabric-api:fabric-api:$fabric_api_version"

    implementation project(":fabric")

    localRuntime libs.modmenu
}

loom {
    mods {
        testmod {
            sourceSet sourceSets.main
        }
    }

    runs {
        remove server

        client {
            client()
            setConfigName('Fabric Client Test')
            ideConfigGenerated(true)
            runDir('run/testmod')
        }
    }
}
