import me.modmuss50.mpp.ReleaseType

plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
    id 'me.modmuss50.mod-publish-plugin'
    id 'publish-local'
}

loom {
    def aw = file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }

    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }

    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('run/client')
            source sourceSets.main
        }
    }
}

repositories {
    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/"
    }
    exclusiveContent {
        forRepository {
            maven {
                name = "fishstiz"
                url = "https://raw.githubusercontent.com/fishstiz/maven/m2"
            }
        }
        filter {
            includeModule ("io.github.fishstiz", "minecraft-cursor-fabric")
            includeModule ("io.github.fishstiz", "minecraft-cursor-fabric-api")
        }
    }
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
    maven { url = "https://maven.frohnmeyer-wds.de/artifacts" }
}

dependencies {
    api project(path: ":api:fabric", configuration: "namedElements")
    include(project(path: ":api:fabric"))

    modApi libs.fidgetz.fabric
    include(libs.fidgetz.fabric)

    minecraft "com.mojang:minecraft:$minecraft_version"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-$minecraft_version:$parchment_version@zip")
    }

    modImplementation "net.fabricmc:fabric-loader:$fabric_loader_version"
    modImplementation "net.fabricmc.fabric-api:fabric-api:$fabric_api_version"

    modCompileOnly libs.modmenu
    modLocalRuntime libs.modmenu

    modCompileOnly libs.minecraftCursor.fabric.api
    modLocalRuntime libs.minecraftCursor.fabric

    modCompileOnly libs.resourcify
    modCompileOnly libs.bundles.respackopts
}

publishMods {
    dryRun = Boolean.valueOf(dry_run)
    type = ReleaseType.of(release_type)
    changelog = rootProject.file("CHANGELOG.md").text
    displayName = "Fabric v${this.version}"
    file = jar.archiveFile
    additionalFiles.from(sourcesJar.archiveFile)
    modLoaders.add("fabric")

    github {
        parent rootProject.tasks.named("publishGithub")
    }

    modrinth {
        accessToken = findProperty("MODRINTH_TOKEN") ?: ""
        projectId = modrinth_id
        minecraftVersions.addAll(modrinth_versions.split(','))
        requires("fabric-api")
    }

    curseforge {
        accessToken = findProperty("CURSEFORGE_TOKEN") ?: ""
        projectId = curseforge_id
        minecraftVersions.addAll(curseforge_versions.split(','))
        client = true
        requires("fabric-api")
    }
}
