import me.modmuss50.mpp.PublishOptions
import me.modmuss50.mpp.ReleaseType
import me.modmuss50.mpp.platforms.curseforge.CurseforgeOptions
import me.modmuss50.mpp.platforms.github.GithubOptions
import me.modmuss50.mpp.platforms.modrinth.ModrinthOptions

plugins {
    id 'multiloader-loader'
    id 'net.fabricmc.fabric-loom'
    id 'me.modmuss50.mod-publish-plugin'
    id 'publish-local'
}

sourceSets {
    testmod {
        compileClasspath += main.compileClasspath
        runtimeClasspath += main.runtimeClasspath
    }
}

loader {
    sources = [sourceSets.main, sourceSets.testmod]
}

loom {
    def aw = file("src/main/resources/${mod_id}.classtweaker")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
        testmod {
            sourceSet sourceSets.testmod
        }
    }

    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('run/client')
            source sourceSets.main
        }
        testmodClient {
            client()
            setConfigName('Fabric Client Test')
            ideConfigGenerated(true)
            runDir('run/testmod')
            source sourceSets.testmod
        }
    }
}

repositories {
    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/"
    }
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
    maven { url = "https://maven.frohnmeyer-wds.de/artifacts" }
}

dependencies {
    api(project(path: ":fidgetz:fabric"))
    include(project(path: ":fidgetz:fabric"))

    api project(path: ":api:fabric")
    include(project(path: ":api:fabric"))

    minecraft "com.mojang:minecraft:$minecraft_version"

    implementation "net.fabricmc:fabric-loader:$fabric_loader_version"
    implementation "net.fabricmc.fabric-api:fabric-api:$fabric_api_version"

    // Mod Compatibility
    compileOnly "com.terraformersmc:modmenu:$modmenu_version"
    localRuntime "com.terraformersmc:modmenu:$modmenu_version"

    compileOnly "maven.modrinth:resourcify:$resourcify_version"
    compileOnly "maven.modrinth:respackopts:$respackopts_version"
    compileOnly "dev.jfronny.libjf:libjf-resource-pack-entry-widgets-v0:$libjf_resource_pack_entry_widgets_version"
    compileOnly "maven.modrinth:polytone:$polytone_version"
}

publishMods {
    dryRun = rootProject["publishOptions"]["dryRun"] as boolean
    type = rootProject["publishOptions"]["type"] as ReleaseType
    changelog = rootProject["publishOptions"]["changelog"] as String

    def publishOptions = publishOptions {
        file = jar.archiveFile
        additionalFiles.from(sourcesJar.archiveFile)
        displayName = "Fabric v${this.version}"
        modLoaders.add("fabric")
    }

    github {
        from rootProject["publishOptions"]["github"] as Provider<GithubOptions>, publishOptions as Provider<PublishOptions>
        parent rootProject.tasks.named("publishGithub")
    }

    modrinth {
        from rootProject["publishOptions"]["modrinth"] as Provider<ModrinthOptions>, publishOptions as Provider<PublishOptions>
        requires("fabric-api")
    }

    curseforge {
        from rootProject["publishOptions"]["curseforge"] as Provider<CurseforgeOptions>, publishOptions as Provider<PublishOptions>
        requires("fabric-api")
    }
}
