plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
    id 'publish-local'
}

loader {
    common = ':fidgetz:common'
}

neoForge {
    version = neoforge_version

    def at = project(loader.common).file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }

    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}
