plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
    id 'publish-local'
}

loader {
    commonPath = ':api:common'
}

dependencies {
    minecraft "com.mojang:minecraft:$minecraft_version"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-$minecraft_version:$parchment_version@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:$fabric_loader_version"
    modImplementation "net.fabricmc.fabric-api:fabric-api:$fabric_api_version"
}

loom {
    runs {
        remove client
        remove server
    }
}
