import me.modmuss50.mpp.ReleaseType

plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
    id 'me.modmuss50.mod-publish-plugin'
    id 'publish-local'
}

neoForge {
    version = neoforge_version

    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }

    parchment {
        minecraftVersion = minecraft_version
        mappingsVersion = parchment_version
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }

    runs {
        client {
            type = "client"
            gameDirectory = project.file('run/client')
            ideName = "NeoForge Client ($project.path)"
        }
    }
}

repositories {
    exclusiveContent {
        forRepository {
            maven {
                name = "fishstiz"
                url = "https://raw.githubusercontent.com/fishstiz/maven/m2"
            }
        }
        filter {
            includeModule ("io.github.fishstiz", "minecraft-cursor-neoforge")
            includeModule ("io.github.fishstiz", "minecraft-cursor-common-api")
        }
    }
    maven { url = "https://maven.frohnmeyer-wds.de/artifacts" }
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    api jarJar(project(path: ":api:neoforge"))

    api libs.fidgetz.neoforge
    jarJar(libs.fidgetz.neoforge)

    compileOnly libs.minecraftCursor.common.api
    localRuntime libs.minecraftCursor.neoforge

    compileOnly libs.resourcify
    compileOnly libs.bundles.respackopts
}

publishMods {
    dryRun = Boolean.valueOf(dry_run)
    type = ReleaseType.of(release_type)
    changelog = rootProject.file("CHANGELOG.md").text
    file = jar.archiveFile
    additionalFiles.from(sourcesJar.archiveFile)
    displayName = "NeoForge v${this.version}"
    modLoaders.add("neoforge")

    github {
        parent rootProject.tasks.named("publishGithub")
    }

    modrinth {
        accessToken = findProperty("MODRINTH_TOKEN") ?: ""
        minecraftVersions.addAll(modrinth_versions.split(','))
        projectId = modrinth_id
    }

    curseforge {
        accessToken = findProperty("CURSEFORGE_TOKEN") ?: ""
        projectId = curseforge_id
        minecraftVersions.addAll(curseforge_versions.split(','))
        client = true
    }
}
