plugins {
    id 'multiloader-common-provider'
    id 'net.neoforged.moddev'
}

neoForge {
    neoFormVersion = neo_form_version

    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }

    parchment {
        minecraftVersion = minecraft_version
        mappingsVersion = parchment_version
    }
}

repositories {
    exclusiveContent {
        forRepository {
            maven {
                name = "fishstiz"
                url = "https://raw.githubusercontent.com/fishstiz/maven/m2"
            }
        }
        filter {
            includeModule ("io.github.fishstiz", "minecraft-cursor-common-api")
        }
    }
    maven { url = "https://maven.frohnmeyer-wds.de/artifacts" }
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
}

dependencies {
    compileOnlyApi project(path: ":api:common")
    compileOnlyApi libs.fidgetz.common

    compileOnly libs.bundles.mixin
    annotationProcessor libs.mixin.extras

    compileOnly libs.minecraftCursor.common.api
    compileOnly libs.resourcify
    compileOnly libs.bundles.respackopts
}
